DROP TABLE IF EXISTS country_codes CASCADE;
DROP TABLE IF EXISTS oscar_awards;
DROP TABLE IF EXISTS country_details;

-- Create table for country codes dataset
CREATE TABLE country_codes(
	COUNTRY VARCHAR(100) PRIMARY KEY NOT NULL,
	CODE VARCHAR(2),
	UNIQUE(CODE)
);

-- Create table to load oscars dataset
CREATE TABLE oscar_awards(
	ID SERIAL PRIMARY KEY NOT NULL,
	MOVIE VARCHAR(100) NOT NULL,
	FIRSTNAME VARCHAR(30) NOT NULL,
	LASTNAME VARCHAR(30),
	AWARD VARCHAR(30) NOT NULL,
	YEAROFAWARD VARCHAR(4) NOT NULL,
	BIRTHCOUNTRY VARCHAR(30) NOT NULL,
	FOREIGN KEY(BIRTHCOUNTRY) REFERENCES country_codes(COUNTRY),
	BIRTHYEAR VARCHAR(4) NOT NULL,
	BIOURL VARCHAR(100) NOT NULL
);

-- Create table to load country details
CREATE TABLE country_details(
	COUNTRYCODE VARCHAR(2) PRIMARY KEY NOT NULL,
	FOREIGN KEY (COUNTRYCODE) REFERENCES country_codes(CODE),
	REGION VARCHAR(30) NOT NULL,
	INCOMELEVEL VARCHAR(30) NOT NULL,
	CAPITAL VARCHAR(30) NOT NULL
);